[package]
name = "serde_robust"
version = "0.1.0"
authors = ["Jesse Hoobergs <jesse@codebergs.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]

[dev-dependencies]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
